### ISSUE TITLE
table中使用查询表单问题

### ISSUE THREAD

**Issue by katiua** [ashuicoder/naive-ui-components#13]
在table中使用查询表单时, 如果props的类型为select, 自带的重置按钮无法清除选中的值, 仍会携带在请求中.

**Comment by autumnLeaves-lady** [comment]
> 在table中使用查询表单时, 如果props的类型为select, 自带的重置按钮无法清除选中的值, 仍会携带在请求中.

我们自使用不会出现这个情况，查看下是否是设置了defaultValue
