### ISSUE TITLE
共创/反馈讨论组

### ISSUE THREAD

**Issue by mryfan** [ashuicoder/naive-ui-components#2]
你好 能加一下联系方式或者讨论组之类的么

**Comment by autumnLeaves-lady** [comment]
已优化，size可由外部传入，以控制内部的size

**Comment by mryfan** [comment]
不是，铁子，你这多久上线一次啊

**Comment by autumnLeaves-lady** [comment]
天天在线的嘛

**Comment by mryfan** [comment]
铁子   你能不能创建个群哇， 要不然我反馈个问题，你这忒久了。我都怀疑你故意不看的

**Comment by autumnLeaves-lady** [comment]
之前太忙了，但以后会经常看的。有评论我们立即会收到邮件通知。反馈直接提个issue，我们有时间都会来改的。
