### ISSUE TITLE
type: 'input' 能否支持前缀 & 后缀

### ISSUE THREAD

**Issue by lkeme** [ashuicoder/naive-ui-components#5]
```vue
<template #prefix>
    <n-icon :component="FlashOutline" />
  </template>
 <template #suffix>
    元
  </template>
```

以方便插入ICON

**Comment by mryfan** [comment]
fork后 自己修复吧 
![00E7A4A8](https://github.com/ashuicoder/naive-ui-components/assets/28995283/aa0ae350-d61e-41cb-a8b6-1a935f9d1522)

**Comment by ashuicoder** [comment]
> ```
> <template #prefix>
>     <n-icon :component="FlashOutline" />
>   </template>
>  <template #suffix>
>     元
>   </template>
> ```
> 
> 以方便插入ICON

可以使用slot方式来实现
