### ISSUE TITLE
NaiveUiUpload能否给个选项。控制显示或者隐藏size和accept

### ISSUE THREAD

**Issue by zhoubapi999** [ashuicoder/naive-ui-components#6]
有时候设置了accept但是并不想显示对应的文案

**Comment by ashuicoder** [comment]
> 有时候设置了accept但是并不想显示对应的文案

有props的showInfo字段来控制的嘛

**Comment by zhoubapi999** [comment]
> > 有时设置了接受但又不想显示对应的文案
> 
> 有props的showInfo字段来控制的嘛

我看代码showInfo是没用到的

**Comment by ashuicoder** [comment]
> > > 有时设置了接受但又不想显示对应的文案
> > 
> > 
> > 有props的showInfo字段来控制的嘛
> 
> 我看代码showInfo是没用到的

等我这两天看看，有问题修复发个版
