### ISSUE TITLE
动态表单样式问题

### ISSUE THREAD

**Issue by zha-ji-tui** [ashuicoder/naive-ui-components#7]
"naive-ui-form": "^3.0.16"
![image](https://github.com/user-attachments/assets/86f25ecd-cae2-4cee-9277-65d9f18e2c0e)
如图，每次新增的一行都会往前偏移

**Comment by ashuicoder** [comment]
> "naive-ui-form": "^3.0.16" ![image](https://private-user-images.githubusercontent.com/55472948/355330824-86f25ecd-cae2-4cee-9277-65d9f18e2c0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjQ4MDgsIm5iZiI6MTcyMjkyNDUwOCwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzA4MjQtODZmMjVlY2QtY2FlMi00Y2VlLTkyNzctNjVkOWYxOGUyYzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2MDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NThhMGNiMTBjMjg0NTc0YWM0YTIxYjcwYTlkYjcxODEyZDE5NDJhODhkMjQwMzgzZDk2Zjg0YmJlN2IzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1L2xn84mxqhbQatIPM3MIMgxxUhkl3A3ISm7JBOATtw) 如图，每次新增的一行都会往前偏移

确实有这个问题，请等待后续版本修复

**Comment by ashuicoder** [comment]
> "naive-ui-form": "^3.0.16" ![image](https://private-user-images.githubusercontent.com/55472948/355330824-86f25ecd-cae2-4cee-9277-65d9f18e2c0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTY3MjQsIm5iZiI6MTczMDg1NjQyNCwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzA4MjQtODZmMjVlY2QtY2FlMi00Y2VlLTkyNzctNjVkOWYxOGUyYzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAxMjcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NDlmODYwYTZhMzc2NGYxYzdmMDA5NTEwY2Y4NmQ1YTE1OTQ3Mjc3ZTZiNTZiNDNjNDU0NDA1ODBkZWQwZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BZSSpS6kCONqZqTG_jmZbcX4MNeoL_LTzK0VYq5m93U) 如图，每次新增的一行都会往前偏移

由于naive-ui的NForm设置了labelWidth: 'auto'后，会导致子项目的labelWidth的值失效，解决办法是naive-ui-form传props `labelWidth: undefined`
