### ISSUE TITLE
type: 'custom' 报错

### ISSUE THREAD

**Issue by zha-ji-tui** [ashuicoder/naive-ui-components#8]
![image](https://github.com/user-attachments/assets/17141f49-2d48-45de-a602-3f8707fc1428)
![image](https://github.com/user-attachments/assets/b9ccbcc6-fbbe-4642-af84-067dbee87578)
如图，我复制的文档的

**Comment by ashuicoder** [comment]
> ![image](https://private-user-images.githubusercontent.com/55472948/355336009-17141f49-2d48-45de-a602-3f8707fc1428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYwMDktMTcxNDFmNDktMmQ0OC00NWRlLWE2MDItM2Y4NzA3ZmMxNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzc2YmI1MDU5ZjY3NDUxNzI1MTI2YmRjMDBjMTJmMmM4ZTM3MWM4NzU4OWUyMmYzZTMyNmI1NTY3MGNmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KhDB8FGTO7PIOhI1zv9c9GGj1Nx-L1cOkd0S2YKo_x4) ![image](https://private-user-images.githubusercontent.com/55472948/355336199-b9ccbcc6-fbbe-4642-af84-067dbee87578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYxOTktYjljY2JjYzYtZmJiZS00NjQyLWFmODQtMDY3ZGJlZTg3NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZGUzODFiMmQwMzI4NjNhMjkyN2JjZjI3ZTNjNTc3MmIzODQ4NzA0YzE5YzY0MTEzYjA1YTA1MmFhYjNmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mZHFi8mDEg7l0RueLK3yJWr8yWGrqA40Wa-spWUqfg) 如图，我复制的文档的

文档没有写custom了嘛，用slot代替

**Comment by zha-ji-tui** [comment]
> > ![image](https://private-user-images.githubusercontent.com/55472948/355336009-17141f49-2d48-45de-a602-3f8707fc1428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYwMDktMTcxNDFmNDktMmQ0OC00NWRlLWE2MDItM2Y4NzA3ZmMxNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzc2YmI1MDU5ZjY3NDUxNzI1MTI2YmRjMDBjMTJmMmM4ZTM3MWM4NzU4OWUyMmYzZTMyNmI1NTY3MGNmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KhDB8FGTO7PIOhI1zv9c9GGj1Nx-L1cOkd0S2YKo_x4) ![image](https://private-user-images.githubusercontent.com/55472948/355336199-b9ccbcc6-fbbe-4642-af84-067dbee87578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYxOTktYjljY2JjYzYtZmJiZS00NjQyLWFmODQtMDY3ZGJlZTg3NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZGUzODFiMmQwMzI4NjNhMjkyN2JjZjI3ZTNjNTc3MmIzODQ4NzA0YzE5YzY0MTEzYjA1YTA1MmFhYjNmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mZHFi8mDEg7l0RueLK3yJWr8yWGrqA40Wa-spWUqfg) 如图，我复制的文档的
> 
> 文档没有写custom了嘛，用slot代替

那文档需要更新下哦

**Comment by ashuicoder** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/55472948/355336009-17141f49-2d48-45de-a602-3f8707fc1428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYwMDktMTcxNDFmNDktMmQ0OC00NWRlLWE2MDItM2Y4NzA3ZmMxNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzc2YmI1MDU5ZjY3NDUxNzI1MTI2YmRjMDBjMTJmMmM4ZTM3MWM4NzU4OWUyMmYzZTMyNmI1NTY3MGNmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KhDB8FGTO7PIOhI1zv9c9GGj1Nx-L1cOkd0S2YKo_x4) ![image](https://private-user-images.githubusercontent.com/55472948/355336199-b9ccbcc6-fbbe-4642-af84-067dbee87578.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjY4NjYsIm5iZiI6MTcyMjkyNjU2NiwicGF0aCI6Ii81NTQ3Mjk0OC8zNTUzMzYxOTktYjljY2JjYzYtZmJiZS00NjQyLWFmODQtMDY3ZGJlZTg3NTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA2NDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZGUzODFiMmQwMzI4NjNhMjkyN2JjZjI3ZTNjNTc3MmIzODQ4NzA0YzE5YzY0MTEzYjA1YTA1MmFhYjNmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4mZHFi8mDEg7l0RueLK3yJWr8yWGrqA40Wa-spWUqfg) 如图，我复制的文档的
> > 
> > 
> > 文档没有写custom了嘛，用slot代替
> 
> 那文档需要更新下哦

文档已经更新的，应该是你的浏览器缓存
